export type{default as CategoriesType} from "./CategoriesType"
export type{default as NewsCardType} from "./NewsCardType"
export type{default as SliderItemType} from "./SliderItemType"
export type{default as HomeSlirderType} from "./HomeSlirderType"
export type{default as ExclusiveType} from "./ExclusiveType"
export type{default as PostType} from "./PostType"
export type{default as AboutType} from "./AboutType"
export * from "./live-facebook"