export * from "./categories"
export * from "./latest-news"
export * from "./most-popular"
export *from "./most-read"
export * from "./slider"
export * from "./exclusives"
export * from "./today-picks"
export* from "./category-news"
export * from "./get-post"
export * from "./about-us"
export * from "./wether"
export * from "./Social-media"
export * from "./Subscribe"